# Generated by Django 5.1.2 on 2026-01-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100)),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('duration', models.IntegerField()),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_node', to='routes.airport')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_node', to='routes.airport')),
            ],
        ),
    ]
